openapi: 3.0.3
info:
  title: Porto Taxi Real-Time Simulation API
  description: |
    REST API for simulating real-time taxi trip data from Porto, Portugal.
    
    ## Authentication
    All endpoints (except /health) require two headers:
    - `x-api-key`: Your API key
    - `x-group-name`: Your group identifier
    
  version: 1.0.0
  contact:
    name: API Support
  license:
    name: MIT

servers:
  - url: http://localhost:8000
    description: Local development
  - url: https://api.example.com
    description: Production

paths:
  /health:
    get:
      summary: Health check
      description: Returns the health status of the API and whether data is loaded
      operationId: healthCheck
      tags:
        - System
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy
                  data_loaded:
                    type: boolean
                    example: true
        '503':
          description: Service is unhealthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: unhealthy
                  data_loaded:
                    type: boolean
                    example: false

  /drivers:
    get:
      summary: List taxi drivers
      description: Returns a paginated list of all taxi drivers in the system
      operationId: listDrivers
      tags:
        - Drivers
      parameters:
        - name: limit
          in: query
          description: Maximum number of drivers to return
          required: false
          schema:
            type: integer
            default: 100
            minimum: 1
            maximum: 1000
        - name: offset
          in: query
          description: Number of drivers to skip
          required: false
          schema:
            type: integer
            default: 0
            minimum: 0
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                    description: Total number of drivers
                    example: 442
                  limit:
                    type: integer
                    example: 100
                  offset:
                    type: integer
                    example: 0
                  count:
                    type: integer
                    description: Number of drivers in this response
                    example: 100
                  drivers:
                    type: array
                    items:
                      $ref: '#/components/schemas/Driver'
        '503':
          description: Data not loaded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /trips:
    get:
      summary: List trips
      description: Returns a paginated list of trips with optional filters
      operationId: listTrips
      tags:
        - Trips
      parameters:
        - name: limit
          in: query
          description: Maximum number of trips to return
          required: false
          schema:
            type: integer
            default: 100
            minimum: 1
            maximum: 1000
        - name: offset
          in: query
          description: Number of trips to skip
          required: false
          schema:
            type: integer
            default: 0
            minimum: 0
        - name: driver_id
          in: query
          description: Filter by taxi driver ID
          required: false
          schema:
            type: integer
            example: 20000589
        - name: date
          in: query
          description: Filter by date (Unix timestamp in seconds)
          required: false
          schema:
            type: integer
            example: 1372636858
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                    description: Total number of trips matching filters
                    example: 1500
                  limit:
                    type: integer
                    example: 100
                  offset:
                    type: integer
                    example: 0
                  count:
                    type: integer
                    description: Number of trips in this response
                    example: 100
                  filters:
                    type: object
                    properties:
                      driver_id:
                        type: integer
                        nullable: true
                        example: 20000589
                      date:
                        type: integer
                        nullable: true
                        example: 1372636858
                  trips:
                    type: array
                    items:
                      $ref: '#/components/schemas/Trip'
        '404':
          description: No trips found with specified filters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '503':
          description: Data not loaded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /live:
    get:
      summary: Get all active trips (live simulation)
      description: |
        Returns all trips currently active in the simulation.
        The simulation replays the 2-hour window from 2013-11-26 08:00-10:00 in real-time,
        repeating every 2 hours starting at odd hours (01:00, 03:00, 05:00, etc.).
        GPS positions are shown progressively (one every 15 seconds).
      operationId: liveAll
      tags:
        - Live Simulation
      parameters:
        - name: driver_id
          in: query
          description: Optional filter by taxi driver ID
          required: false
          schema:
            type: integer
            example: 20000589
      responses:
        '200':
          description: Active trips at current simulation time
          content:
            application/json:
              schema:
                type: object
                properties:
                  simulation_time:
                    type: integer
                    description: Current simulation timestamp (Unix epoch)
                    example: 1385456400
                  real_time:
                    type: string
                    format: date-time
                    description: Current real time (ISO 8601)
                    example: "2026-02-28T17:01:00Z"
                  seconds_into_cycle:
                    type: integer
                    description: Seconds elapsed in current 2-hour cycle
                    example: 60
                  active_trips:
                    type: integer
                    description: Number of active trips
                    example: 45
                  trips:
                    type: array
                    items:
                      $ref: '#/components/schemas/LiveTrip'
        '404':
          description: No active trips at current simulation time
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '503':
          description: Data not loaded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /live/{driver_id}:
    get:
      summary: Get active trips for specific driver
      description: Returns active trips for a specific driver at current simulation time
      operationId: liveDriver
      tags:
        - Live Simulation
      parameters:
        - name: driver_id
          in: path
          description: Taxi driver ID
          required: true
          schema:
            type: integer
            example: 20000589
      responses:
        '200':
          description: Active trips for the driver
          content:
            application/json:
              schema:
                type: object
                properties:
                  simulation_time:
                    type: integer
                    example: 1385456400
                  real_time:
                    type: string
                    format: date-time
                    example: "2026-02-28T17:01:00Z"
                  seconds_into_cycle:
                    type: integer
                    example: 60
                  active_trips:
                    type: integer
                    example: 1
                  trips:
                    type: array
                    items:
                      $ref: '#/components/schemas/LiveTrip'
        '404':
          description: Driver has no active trips
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /live/{driver_id}/latest:
    get:
      summary: Get latest GPS position for driver
      description: Returns only the current GPS position without history
      operationId: liveDriverLatest
      tags:
        - Live Simulation
      parameters:
        - name: driver_id
          in: path
          description: Taxi driver ID
          required: true
          schema:
            type: integer
            example: 20000589
      responses:
        '200':
          description: Current position and trip details
          content:
            application/json:
              schema:
                type: object
                properties:
                  simulation_time:
                    type: integer
                    example: 1385456400
                  real_time:
                    type: string
                    format: date-time
                    example: "2026-02-28T17:01:00Z"
                  driver_id:
                    type: integer
                    example: 20000589
                  trip_id:
                    type: integer
                    example: 1372636858620000589
                  elapsed_seconds:
                    type: integer
                    description: Seconds elapsed since trip start
                    example: 120
                  total_duration:
                    type: integer
                    description: Total trip duration in seconds
                    example: 600
                  progress_pct:
                    type: number
                    format: float
                    description: Trip progress percentage
                    example: 20.0
                  current_position:
                    type: array
                    description: Current GPS coordinates [longitude, latitude]
                    items:
                      type: number
                      format: float
                    example: [-8.618643, 41.141412]
                  trip_details:
                    $ref: '#/components/schemas/TripDetails'
        '404':
          description: Driver has no active trip
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /live/{driver_id}/trip/{trip_id}:
    get:
      summary: Get specific trip with GPS history
      description: Returns detailed information for a specific trip including GPS history
      operationId: liveDriverTrip
      tags:
        - Live Simulation
      parameters:
        - name: driver_id
          in: path
          description: Taxi driver ID
          required: true
          schema:
            type: integer
            example: 20000589
        - name: trip_id
          in: path
          description: Trip ID
          required: true
          schema:
            type: integer
            example: 1372636858620000589
      responses:
        '200':
          description: Trip details with GPS history
          content:
            application/json:
              schema:
                type: object
                properties:
                  simulation_time:
                    type: integer
                    example: 1385456400
                  real_time:
                    type: string
                    format: date-time
                    example: "2026-02-28T17:01:00Z"
                  driver_id:
                    type: integer
                    example: 20000589
                  trip_id:
                    type: integer
                    example: 1372636858620000589
                  elapsed_seconds:
                    type: integer
                    example: 120
                  total_duration:
                    type: integer
                    example: 600
                  progress_pct:
                    type: number
                    format: float
                    example: 20.0
                  gps_history:
                    type: array
                    description: GPS coordinates history (one every 15 seconds)
                    items:
                      type: array
                      items:
                        type: number
                        format: float
                    example: [[-8.618643, 41.141412], [-8.618499, 41.141376]]
                  current_position:
                    type: array
                    items:
                      type: number
                      format: float
                    example: [-8.618499, 41.141376]
                  trip_data:
                    type: object
                    description: Complete trip data
        '404':
          description: Trip not found or not active
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Driver:
      type: object
      properties:
        TAXI_ID:
          type: integer
          description: Unique taxi identifier
          example: 20000589
        fuel_type:
          type: string
          description: Vehicle fuel type
          enum: [diesel, hybrid, electric, lpg, gasoline]
          example: hybrid
        vehicle_year:
          type: integer
          description: Vehicle manufacturing year
          example: 2012
        comfort_base:
          type: number
          format: float
          description: Base comfort rating
          example: 4.1
        driver_rating:
          type: number
          format: float
          description: Average driver rating
          example: 4.04
    
    Trip:
      type: object
      properties:
        TRIP_ID:
          type: integer
          description: Unique trip identifier
          example: 1372636858620000589
        TAXI_ID:
          type: integer
          description: Taxi driver identifier
          example: 20000589
        TIMESTAMP:
          type: integer
          description: Trip start time (Unix epoch seconds)
          example: 1372636858
        CALL_TYPE:
          type: string
          description: How the trip was requested
          enum: [A, B, C]
          example: C
        DAY_TYPE:
          type: string
          description: Type of day
          enum: [A, B, C]
          example: A
        MISSING_DATA:
          type: boolean
          description: Whether GPS data is missing
          example: false
        passengers:
          type: integer
          description: Number of passengers
          example: 2
        fare:
          type: number
          format: float
          description: Trip fare in euros
          example: 12.50
        distance_km:
          type: number
          format: float
          description: Trip distance in kilometres
          example: 5.5
        duration_min:
          type: number
          format: float
          description: Trip duration in minutes
          example: 12.2
    
    Error:
      type: object
      properties:
        error:
          type: string
          example: Data not loaded
    
    TripDetails:
      type: object
      properties:
        call_type:
          type: string
          enum: [A, B, C]
          example: C
        passengers:
          type: integer
          nullable: true
          example: 2
        fare:
          type: number
          format: float
          nullable: true
          example: 12.50
        payment:
          type: string
          nullable: true
          enum: [cash, card]
          example: cash
        purpose:
          type: string
          nullable: true
          enum: [work, leisure]
          example: work
        fuel_type:
          type: string
          nullable: true
          enum: [diesel, hybrid, electric, lpg, gasoline]
          example: hybrid
    
    LiveTrip:
      type: object
      properties:
        driver_id:
          type: integer
          example: 20000589
        trip_id:
          type: integer
          example: 1372636858620000589
        elapsed_seconds:
          type: integer
          description: Seconds elapsed since trip start
          example: 120
        total_duration:
          type: integer
          description: Total trip duration in seconds
          example: 600
        progress_pct:
          type: number
          format: float
          description: Trip progress percentage
          example: 20.0
        trip_details:
          $ref: '#/components/schemas/TripDetails'
        gps_history:
          type: array
          description: GPS coordinates history (one every 15 seconds)
          items:
            type: array
            items:
              type: number
              format: float
          example: [[-8.618643, 41.141412], [-8.618499, 41.141376]]
        current_position:
          type: array
          description: Current GPS coordinates [longitude, latitude]
          items:
            type: number
            format: float
          example: [-8.618499, 41.141376]

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
    GroupAuth:
      type: apiKey
      in: header
      name: x-group-name

security:
  - ApiKeyAuth: []
    GroupAuth: []
